# Generated by Django 5.2.1 on 2025-07-28 15:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_subscriptionplan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenthistory',
            old_name='pay_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='paymenthistory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='started_at',
        ),
        migrations.AddField(
            model_name='paymenthistory',
            name='fail_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='start_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='ref_id',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='paymenthistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
