# Generated by Django 5.2.1 on 2025-07-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.RenameField(
            model_name='plant',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='next_watering',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(default=7, help_text='How often to water (in days)'),
        ),
        migrations.AddField(
            model_name='plantdiagnosis',
            name='category',
            field=models.CharField(choices=[('fungus', 'Fungus'), ('pest', 'Pest'), ('watering', 'Watering'), ('light', 'Light'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='plantdiagnosis',
            name='confidence',
            field=models.FloatField(default=0.0),
        ),
    ]
