# Generated by Django 5.2.1 on 2025-07-11 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0002_alter_plant_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watered_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, help_text='توضیح اختیاری درباره آبیاری (مثلاً نوع آب یا شرایط خاص)')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='plants.plant')),
            ],
            options={
                'ordering': ['-watered_at'],
            },
        ),
    ]
