# Generated by Django 5.2.1 on 2025-07-15 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('plants', '0003_wateringlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField(help_text='آبیاری هر چند روز یک\u200cبار')),
                ('plant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watering_schedule', to='plants.plant')),
                ('schedule', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='django_celery_beat.periodictask')),
            ],
        ),
    ]
