# Generated by Django 5.2.1 on 2025-07-16 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        ('plants', '0004_wateringschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Plant', 'verbose_name_plural': 'Plants'},
        ),
        migrations.AlterModelOptions(
            name='plantdiagnosis',
            options={'ordering': ['-created_at'], 'verbose_name': 'Plant Diagnosis', 'verbose_name_plural': 'Plant Diagnoses'},
        ),
        migrations.AlterModelOptions(
            name='wateringlog',
            options={'ordering': ['-watered_at'], 'verbose_name': 'Watering Log', 'verbose_name_plural': 'Watering Logs'},
        ),
        migrations.AddField(
            model_name='plant',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(upload_to='plants/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateField(blank=True, null=True, verbose_name='Last Watered'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Plant Name'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='next_watering',
            field=models.DateField(blank=True, null=True, verbose_name='Next Watering'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='species',
            field=models.CharField(blank=True, max_length=100, verbose_name='Species'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Uploaded At'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='watering_frequency',
            field=models.IntegerField(default=7, help_text='How often to water (in days)', verbose_name='Watering Frequency'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='care_instructions',
            field=models.TextField(verbose_name='Care Instructions'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='category',
            field=models.CharField(choices=[('fungus', 'Fungus'), ('pest', 'Pest'), ('watering', 'Watering'), ('light', 'Light'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='confidence',
            field=models.FloatField(default=0.0, verbose_name='Confidence'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='diagnosis',
            field=models.TextField(verbose_name='Diagnosis Result'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='image',
            field=models.ImageField(upload_to='diagnoses/', verbose_name='Diagnosis Image'),
        ),
        migrations.AlterField(
            model_name='plantdiagnosis',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='plants.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='note',
            field=models.TextField(blank=True, help_text='Optional note about watering (e.g., water type or special conditions)', verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watering_logs', to='plants.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='wateringlog',
            name='watered_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Watered At'),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='frequency',
            field=models.IntegerField(help_text='Watering frequency in days', verbose_name='Frequency'),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='plant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watering_schedule', to='plants.plant', verbose_name='Plant'),
        ),
        migrations.AlterField(
            model_name='wateringschedule',
            name='schedule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='django_celery_beat.periodictask', verbose_name='Periodic Task Schedule'),
        ),
    ]
